version: '3'

services:

  node:
    container_name: justfredrik_11ty

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/app

    working_dir: /app

    environment:
      NODE_ENV: development

    ports:
      - '5000:5000'

    command: yarn start
