name: Deploy to prod

on: [push]

jobs:
  deploy:

    name: Deploy to CloudFront

    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout file
        uses: actions/checkout@v2

      - name: Set up caching for npm
        id: cache-npm
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm packages
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: sudo npm -g i html-minify

      - name: Minify HTML
        run: htmlminify index.html -o index.html

      - name: Deploy to Amazon S3
        uses: reggionick/s3-deploy@v2.0.1
        with:
          folder: .
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
