name: Deploy to prod

on: [push]

jobs:
  deploy:

    name: Deploy to CloudFront

    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout file
        uses: actions/checkout@v2

      - name: Minify
        uses: jossydevers/minify-js@v1.0.0
        with:
          directory: index.html
          output: index.html

      - name: Deploy to Amazon S3
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: .
          bucket: ${{ secrets.S3_BUCKET }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: / *
