name: Deploy to prod

on:
  push:
    branches:
      - master

jobs:
  deploy:

    name: Deploy to Cloudflare

    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout file
        uses: actions/checkout@v2

      - name: Minify HTML
        run: |
          sudo npm -g i html-minify
          htmlminify index.html -o index.html

      - name: Timestamp build
        run: |
          echo "<!-- Deployed: `date` -->" >> index.html
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: justfredrik-com
          directory: .
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: master
